(()=>{'use strict';
const $=id=>document.getElementById(id);
function loadScript(src,test){return new Promise((resolve,reject)=>{if(test())return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('外部元件載入失敗'));document.head.appendChild(s)})}
function fitNums(){document.querySelectorAll('#profit,#margin,#totalProfit,#quoteUnitProfit,#quoteMargin,#quoteTotalProfit,#qUnit,#qMargin,#qTotal,.quote-field b,.mini-stat b,.stat b,.metric-value,.kpi-value,.kpi b').forEach(el=>{el.style.fontSize='';el.style.whiteSpace='nowrap';el.style.overflow='hidden';const p=el.parentElement,max=Math.max(25,(p?.clientWidth||100)-10);let size=parseFloat(getComputedStyle(el).fontSize)||28;while(el.scrollWidth>max&&size>13){size-=1;el.style.fontSize=size+'px'}})}
function fourRows(root=document){root.querySelectorAll('.q-table tbody').forEach(tb=>{const cols=tb.closest('table')?.tHead?.rows?.[0]?.cells?.length||5;while(tb.rows.length<4){const r=tb.insertRow();for(let i=0;i<cols;i++)r.insertCell().innerHTML='&nbsp;'}})}
function ensureQuoteButtons(){document.querySelectorAll('.quote-card[id^="record-quotes-"]').forEach(card=>{if(card.querySelector('.r70-to-doc,.r70-formal-quote'))return;const id=(card.id.match(/record-quotes-(.+)$/)||[])[1];const actions=card.querySelector('.record-actions');if(!id||!actions)return;const b=document.createElement('button');b.type='button';b.className='customer-link r70-to-doc r70-formal-quote';b.textContent='報價單';b.addEventListener('click',()=>{if(typeof window.openQuoteDocument==='function')window.openQuoteDocument(id)});actions.insertBefore(b,actions.firstChild)})}
function ensureCardLink(){const host=$('customers')?.querySelector('.card');if(!host||$('r70CardOpen'))return;const b=document.createElement('button');b.id='r70CardOpen';b.type='button';b.className='secondary';b.style.width='100%';b.style.marginTop='8px';b.textContent='📇 名片管理';b.onclick=()=>{location.hash='businessCardScan'};host.appendChild(b)}
async function ensurePdfLibs(){await loadScript('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js',()=>!!window.html2canvas);await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf)}
async function pdfQuote(){try{if(typeof window.renderQuoteDocument==='function')window.renderQuoteDocument();if(typeof window.paginateQuotePages==='function')window.paginateQuotePages();fourRows();await ensurePdfLibs();const pages=[...document.querySelectorAll('#quotePages .quote-paper')];if(!pages.length)throw new Error('目前沒有報價單');const PDF=window.jspdf.jsPDF,pdf=new PDF({orientation:'portrait',unit:'mm',format:'a4'});for(let i=0;i<pages.length;i++){const c=pages[i].cloneNode(true);fourRows(c);c.style.transform='none';c.style.width='794px';c.style.minWidth='794px';c.style.maxWidth='794px';c.style.margin='0';c.style.boxShadow='none';c.style.position='fixed';c.style.left='-10000px';c.style.top='0';document.body.appendChild(c);const cv=await window.html2canvas(c,{scale:2,backgroundColor:'#fff',useCORS:true});c.remove();if(i)pdf.addPage();pdf.addImage(cv.toDataURL('image/jpeg',.94),'JPEG',0,0,210,297)}const name=`報價單_${$('qdNo')?.value||new Date().toISOString().slice(0,10)}.pdf`,blob=pdf.output('blob'),file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'報價單 PDF'});return}pdf.save(name)}catch(e){console.error(e);alert('PDF 產生失敗：'+(e?.message||e))}}
function installPdfButton(){document.querySelectorAll('#quoteDocument button').forEach(b=>{if(!/列印|PDF/.test(b.textContent)||b.dataset.r70Pdf==='1')return;b.dataset.r70Pdf='1';b.textContent='產生 PDF／列印';b.onclick=pdfQuote})}
function installCss(){if(document.getElementById('r70-final-runtime-style'))return;const s=document.createElement('style');s.id='r70-final-runtime-style';s.textContent=`.quote-paper .q-party,.quote-paper .q-table,.quote-paper .q-table th,.quote-paper .q-table td,.quote-paper .q-terms,.quote-paper .q-notes{font-size:14pt!important}.quote-paper .q-sales{font-size:15pt!important}.quote-paper .q-table{width:100%!important;table-layout:fixed!important}.quote-paper .q-table th,.quote-paper .q-table td{overflow:hidden!important;overflow-wrap:anywhere!important;word-break:break-word!important}.crm-tools input,.crm-tools select{font-size:16px!important}.r70-candidate-host{position:relative!important}.r70-candidate-box{position:absolute;z-index:99999;left:0;right:0;top:calc(100% + 4px);max-height:250px;overflow:auto;-webkit-overflow-scrolling:touch;background:#0b0f13;border:1px solid #8b672d;border-radius:8px;box-shadow:0 10px 24px rgba(0,0,0,.7);display:none}.r70-candidate-box.show{display:block}.r70-candidate-option{display:block;width:100%;padding:12px 14px;border:0;border-bottom:1px solid #333a41;background:#11171d;color:#eee3d6;text-align:left;font-size:18px;line-height:1.35}.r70-candidate-option:last-child{border-bottom:0}.r70-candidate-option:active{background:#5a3a13}.r70-candidate-empty{padding:11px 14px;color:#a89b8d;font-size:16px}`;document.head.appendChild(s)}
function customerNames(){const out=[];try{const m=JSON.parse(localStorage.getItem('hongbin_crm_master_r70')||'{}');(m.customers||[]).forEach(x=>out.push(String(x?.name||'').trim()))}catch(_){}try{const c=JSON.parse(localStorage.getItem('hongbin_personal_crm_v3')||'{}');(c.customers||[]).forEach(x=>out.push(String(x?.name||'').trim()))}catch(_){}return [...new Set(out.filter(Boolean))]}
function bindCustomerCandidates(){['vCustomer','qCustomer','qdCustomer','pCustomer','cCustomer','mCustomer','tCustomer'].forEach(id=>{const input=$(id);if(!input||input.dataset.r70CustomCandidate==='1')return;input.dataset.r70CustomCandidate='1';input.removeAttribute('list');const host=input.parentElement;if(!host)return;host.classList.add('r70-candidate-host');const box=document.createElement('div');box.className='r70-candidate-box';box.setAttribute('role','listbox');host.appendChild(box);const hide=()=>box.classList.remove('show');const show=()=>{const q=String(input.value||'').trim().toLowerCase().replace(/[\s　]+/g,'');if(!q){hide();return}const matches=customerNames().filter(n=>n.toLowerCase().replace(/[\s　]+/g,'').includes(q)).slice(0,20);box.innerHTML=matches.length?matches.map(n=>`<button type="button" class="r70-candidate-option" data-value="${n.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}">${n.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</button>`).join(''):'<div class="r70-candidate-empty">沒有符合的客戶</div>';box.classList.add('show')};input.addEventListener('input',show);input.addEventListener('focus',()=>{if(input.value.trim())show()});input.addEventListener('blur',()=>setTimeout(hide,180));box.addEventListener('pointerdown',e=>{const b=e.target.closest('.r70-candidate-option');if(!b)return;e.preventDefault();input.value=b.dataset.value||b.textContent.trim();hide();input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));input.focus()})})}
function installShare(){const url=location.origin+location.pathname;window.copyInstallLink=async()=>{try{await navigator.clipboard.writeText(url);alert('安裝連結已複製')}catch(_){prompt('請複製：',url)}};window.shareInstallLink=async()=>{try{if(navigator.share){await navigator.share({title:'鴻繽科技 CRM',url});return}}catch(_){ }window.copyInstallLink()}}
function boot(){installCss();installPdfButton();installShare();ensureQuoteButtons();ensureCardLink();fourRows();fitNums();bindCustomerCandidates();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;installPdfButton();ensureQuoteButtons();ensureCardLink();fourRows();fitNums();bindCustomerCandidates()})}).observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('resize',()=>setTimeout(fitNums,50));window.R70_PDF={pdfQuote,fourRows,fitNums,ensureQuoteButtons}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();