(()=>{'use strict';
const V='R70',MK='hongbin_crm_master_r70',CK='hongbin_crm_cards_r70',$=id=>document.getElementById(id),N=v=>String(v??'').trim().toLowerCase().replace(/[\s　]/g,''),E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
let M={customers:[],products:[],suppliers:[],updatedAt:''},cards=[];try{M=Object.assign(M,JSON.parse(localStorage.getItem(MK)||'{}'))}catch(_){}try{cards=JSON.parse(localStorage.getItem(CK)||'[]');if(!Array.isArray(cards))cards=[]}catch(_){cards=[]}
const saveM=()=>{M.updatedAt=new Date().toISOString();localStorage.setItem(MK,JSON.stringify(M))},saveC=()=>localStorage.setItem(CK,JSON.stringify(cards));
function version(){window.CRM_VERSION=V;document.title='鴻繽科技 CRM｜R70 Integrated Beta';document.querySelectorAll('.content').forEach(x=>{if(/目前版本：R6[89]/.test(x.textContent))x.innerHTML=x.innerHTML.replace(/目前版本：R6[89]/g,'目前版本：R70').replace(/更新日期：[^<\n]*/g,'更新日期：2026-08-26')})}
function loadScript(src,test){return new Promise((ok,ng)=>{if(test())return ok();const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=ng;document.head.appendChild(s)})}
function cByName(n){let q=N(n);return M.customers.find(x=>N(x.name)===q)||null}function pFor(c){let q=N(c);return M.products.filter(x=>!q||N(x.customerName)===q)}
function datalist(id,vals){let d=$(id);if(!d){d=document.createElement('datalist');d.id=id;document.body.appendChild(d)}d.innerHTML=[...new Set(vals.filter(Boolean))].slice(0,3000).map(v=>`<option value="${E(v)}"></option>`).join('')}
function refreshLists(){datalist('r70Customers',M.customers.map(x=>x.name));datalist('r70Products',M.products.flatMap(x=>[x.name,x.customerPartNo,x.supplierPartNo]));datalist('r70Suppliers',M.suppliers.map(x=>x.supplierName));['qCustomer','qdCustomer','vCustomer','pCustomer','cCustomer','mCustomer','tCustomer'].forEach(id=>{let e=$(id);if(e)e.setAttribute('list','r70Customers')});let ps=$('pSupplier');if(ps)ps.setAttribute('list','r70Suppliers')}
function fillCustomer(name,prefix='qd'){let c=cByName(name);if(!c)return false;let map={Contact:'contact',Tel:'tel',Fax:'fax'};for(let [a,b] of Object.entries(map)){let e=$(prefix+a);if(e)e.value=c[b]||''}return true}
function findProduct(c,q){q=N(q);let a=pFor(c);return a.find(x=>[x.name,x.customerPartNo,x.supplierPartNo].some(v=>N(v)===q))||M.products.find(x=>[x.name,x.customerPartNo,x.supplierPartNo].some(v=>N(v)===q))}
function bindEstimate(){let qC=$('qCustomer'),qM=$('qModel'),qN=$('qProductName');[qM,qN].forEach(el=>{if(!el)return;el.setAttribute('list','r70Products');el.addEventListener('change',()=>{let p=findProduct(qC?.value,el.value);if(!p)return;if(qN)qN.value=p.name||'';if(qM)qM.value=p.customerPartNo||p.supplierPartNo||'';if($('qSpec'))$('qSpec').value=p.package||p.unit||'';if($('qPrice')){$('qPrice').value=p.price||'';$('qPrice').dispatchEvent(new Event('input',{bubbles:true}))}if($('qMoq'))$('qMoq').value=p.moq||p.unit||''})});qC?.addEventListener('change',()=>{let c=cByName(qC.value);if(c)refreshLists()})}
function fitNums(){document.querySelectorAll('#profit,#margin,#totalProfit,.quote-field b,.kpi b').forEach(el=>{el.style.fontSize='';el.style.whiteSpace='nowrap';el.style.overflow='hidden';let p=el.parentElement,w=Math.max(25,(p?.clientWidth||100)-10),s=parseFloat(getComputedStyle(el).fontSize)||28;while(el.scrollWidth>w&&s>13){s--;el.style.fontSize=s+'px'}})}
function fourRows(root=document){root.querySelectorAll('.q-table tbody').forEach(tb=>{let cols=tb.closest('table')?.tHead?.rows?.[0]?.cells?.length||5;while(tb.rows.length<4){let r=tb.insertRow();for(let i=0;i<cols;i++){let c=r.insertCell();c.innerHTML='&nbsp;'}}})}
function wrapQuote(){let old=window.renderQuoteDocument;if(old&&!old.__r70){let f=function(){let r=old.apply(this,arguments);fourRows();fitNums();return r};f.__r70=1;window.renderQuoteDocument=f}['openQuoteDocument','openQuoteDocumentFromEstimate'].forEach(k=>{let o=window[k];if(o&&!o.__r70){let f=function(){let r=o.apply(this,arguments);setTimeout(()=>{fillCustomer($('qdCustomer')?.value||'');refreshLists();window.renderQuoteDocument?.()},0);return r};f.__r70=1;window[k]=f}})}
async function ensureXLSX(){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX)}
const pick=(o,...ks)=>{for(let k of ks)if(o[k]!==undefined&&String(o[k]).trim()!=='')return String(o[k]).trim();return''};const good=v=>v&&v!=='-'&&v!=='—';
async function importMaster(file){await ensureXLSX();let wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),res={customers:0,products:0,suppliers:0,skip:0};let rows=n=>wb.Sheets[n]?XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:''}):[];
for(let r of rows('客戶資料')){let x={name:pick(r,'公司名稱','客戶名稱'),address:pick(r,'公司地址','地址'),deliveryAddress:pick(r,'送貨地址'),invoiceAddress:pick(r,'發票地址'),tel:pick(r,'電話','TEL'),fax:pick(r,'傳真','FAX'),taxId:pick(r,'統一編號'),contact:pick(r,'聯繫人','聯絡人'),mobile:pick(r,'聯繫人行動','手機'),invoiceWithGoods:pick(r,'是否隨貨發票'),coa:pick(r,'是否附COA')};if(!(good(x.name)&&good(x.address)&&good(x.tel)&&good(x.contact))){res.skip++;continue}let old=M.customers.find(a=>N(a.name)===N(x.name));old?Object.assign(old,x):M.customers.push(x);res.customers++}
for(let r of rows('供應商資料')){let x={supplierName:pick(r,'供應商名稱'),name:pick(r,'品項','品名'),partNo:pick(r,'品號'),unit:pick(r,'最小包裝單位'),package:pick(r,'包裝')};if(!Object.values(x).every(good)){res.skip++;continue}let old=M.suppliers.find(a=>N(a.supplierName)===N(x.supplierName)&&N(a.partNo)===N(x.partNo));old?Object.assign(old,x):M.suppliers.push(x);res.suppliers++}
for(let r of rows('客戶品項紀錄')){let x={customerName:pick(r,'公司名稱','客戶名稱'),name:pick(r,'品項','品名'),customerPartNo:pick(r,'品號'),supplierPartNo:pick(r,'對應供應商編號'),unit:pick(r,'單位'),price:Number(pick(r,'售價')),coa:pick(r,'隨貨附COA'),invoiceWithGoods:pick(r,'隨貨附發票'),type:pick(r,'類型')};if(!(good(x.customerName)&&good(x.name)&&good(x.customerPartNo)&&good(x.supplierPartNo)&&good(x.unit)&&Number.isFinite(x.price))){res.skip++;continue}let c=M.customers.find(a=>N(a.name)===N(x.customerName)||N(a.name).startsWith(N(x.customerName))||N(x.customerName).startsWith(N(a.name)));if(!c){res.skip++;continue}x.customerName=c.name;let s=M.suppliers.find(a=>N(a.partNo)===N(x.supplierPartNo));if(s){x.supplierName=s.supplierName;x.package=s.package;x.moq=s.unit}let old=M.products.find(a=>N(a.customerName)===N(x.customerName)&&N(a.customerPartNo)===N(x.customerPartNo));old?Object.assign(old,x):M.products.push(x);res.products++}
saveM();refreshLists();renderMaster();alert(`主資料匯入完成\n客戶 ${res.customers}\n產品 ${res.products}\n供應商 ${res.suppliers}\n略過不完整/無對應 ${res.skip}`)}
async function exportMaster(){await ensureXLSX();let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(M.customers),'客戶資料');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(M.products),'客戶品項紀錄');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(M.suppliers),'供應商資料');XLSX.writeFile(wb,`CRM主資料_${new Date().toISOString().slice(0,10)}.xlsx`)}
function renderMaster(){let a=$('r70Counts');if(a)a.textContent=`客戶 ${M.customers.length}｜產品 ${M.products.length}｜供應商 ${M.suppliers.length}`;let q=N($('r70MasterSearch')?.value),b=$('r70MasterResults');if(!b)return;let c=M.customers.filter(x=>!q||N(JSON.stringify(x)).includes(q)).slice(0,20),p=M.products.filter(x=>!q||N(JSON.stringify(x)).includes(q)).slice(0,30),s=M.suppliers.filter(x=>!q||N(JSON.stringify(x)).includes(q)).slice(0,20);b.innerHTML=[...c.map(x=>`<div class="r70-row"><b>客戶</b> ${E(x.name)}｜${E(x.contact)}｜${E(x.tel)}</div>`),...p.map(x=>`<div class="r70-row"><b>產品</b> ${E(x.customerName)}｜${E(x.name)}｜${E(x.customerPartNo)}｜${E(x.supplierName||'')}</div>`),...s.map(x=>`<div class="r70-row"><b>供應商</b> ${E(x.supplierName)}｜${E(x.name)}｜${E(x.partNo)}</div>`)].join('')||'<div class="status">沒有符合資料</div>'}
function masterUI(){let sec=$('settings');if(!sec||$('r70MasterCard'))return;let d=document.createElement('div');d.id='r70MasterCard';d.className='card';d.innerHTML=`<h2 class="section-title">📚 主資料管理</h2><div id="r70Counts" class="content"></div><div class="status">僅匯入完整且可對應的客戶／產品／供應商資料；不猜補缺漏。</div><div style="height:10px"></div><input id="r70Import" type="file" accept=".xlsx,.xls,.csv"><div class="btnrow"><button class="primary" id="r70ImportBtn">匯入 Excel</button><button class="secondary" id="r70ExportBtn">匯出 Excel</button></div><input id="r70MasterSearch" type="search" placeholder="搜尋客戶、產品、品號、供應商"><div id="r70MasterResults"></div>`;sec.insertBefore(d,sec.children[1]||null);$('r70ImportBtn').onclick=()=>{let f=$('r70Import').files[0];if(!f)return alert('請先選擇 Excel 檔');importMaster(f).catch(e=>alert('匯入失敗：'+e.message))};$('r70ExportBtn').onclick=()=>exportMaster().catch(e=>alert('匯出失敗：'+e.message));$('r70MasterSearch').oninput=renderMaster;renderMaster()}
function cardUI(){let sec=$('businessCardScan');if(!sec)return;if(!$('r70CardSave')){let b=document.createElement('button');b.id='r70CardSave';b.className='primary';b.type='button';b.textContent='儲存名片／連結客戶';b.onclick=saveCard;sec.querySelector('.card')?.appendChild(b);let l=document.createElement('div');l.id='r70CardList';l.className='card';sec.appendChild(l)}renderCards();let c=$('customers')?.querySelector('.card');if(c&&!$('r70CardOpen')){let b=document.createElement('button');b.id='r70CardOpen';b.className='secondary';b.style.width='100%';b.style.marginTop='8px';b.textContent='📇 名片管理';b.onclick=()=>location.hash='businessCardScan';c.appendChild(b)}}
function saveCard(){let company=$('bcCompany')?.value.trim(),name=$('bcName')?.value.trim();if(!company||!name)return alert('公司名稱與姓名為必要欄位');let x={id:Date.now(),company,name,title:$('bcTitle')?.value.trim(),mobile:$('bcMobile')?.value.trim(),tel:$('bcTel')?.value.trim(),fax:$('bcFax')?.value.trim(),email:$('bcEmail')?.value.trim(),address:$('bcAddress')?.value.trim(),website:$('bcWebsite')?.value.trim()};let o=cards.find(a=>N(a.company)===N(company)&&N(a.name)===N(name));o?Object.assign(o,x,{id:o.id}):cards.unshift(x);saveC();let c=cByName(company);if(c){c.contact||=name;c.tel||=x.tel;c.fax||=x.fax;c.address||=x.address;saveM()}renderCards();refreshLists();alert('名片已儲存並連結客戶')}
function renderCards(){let b=$('r70CardList');if(b)b.innerHTML=cards.length?'<h2 class="section-title">已儲存名片</h2>'+cards.slice(0,50).map(x=>`<div class="item"><div class="item-title">${E(x.company)}｜${E(x.name)}</div><div class="meta">${E(x.title)}｜${E(x.mobile||x.tel)}｜${E(x.email)}</div></div>`).join(''):'<div class="status">尚無已儲存名片</div>'}
async function ensurePdfLibs(){await loadScript('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js',()=>!!window.html2canvas);await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf)}
async function pdfQuote(){try{window.renderQuoteDocument?.();fourRows();await ensurePdfLibs();let pages=[...document.querySelectorAll('#quotePages .quote-paper')];if(!pages.length)return alert('目前沒有報價單');let PDF=window.jspdf.jsPDF,pdf=new PDF({orientation:'portrait',unit:'mm',format:'a4'});for(let i=0;i<pages.length;i++){let c=pages[i].cloneNode(true);fourRows(c);c.style.transform='none';c.style.width='794px';c.style.minWidth='794px';c.style.margin='0';c.style.boxShadow='none';c.style.position='fixed';c.style.left='-10000px';c.style.top='0';document.body.appendChild(c);let cv=await html2canvas(c,{scale:2,backgroundColor:'#fff',useCORS:true});c.remove();if(i)pdf.addPage();pdf.addImage(cv.toDataURL('image/jpeg',.94),'JPEG',0,0,210,297)}let blob=pdf.output('blob'),file=new File([blob],`報價單_${$('qdNo')?.value||new Date().toISOString().slice(0,10)}.pdf`,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})&&navigator.share)return navigator.share({files:[file],title:'報價單 PDF'});pdf.save(file.name)}catch(e){console.error(e);alert('PDF 產生失敗：'+e.message)}}
function pdfButton(){document.querySelectorAll('#quoteDocument button').forEach(b=>{if(/列印|PDF/.test(b.textContent)){b.textContent='產生 PDF／列印';b.onclick=pdfQuote}})}
function css(){let s=document.createElement('style');s.textContent=`.r70-row{padding:8px 0;border-bottom:1px solid #3d444a;font-size:15px}.quote-paper .q-party,.quote-paper .q-table,.quote-paper .q-table th,.quote-paper .q-table td,.quote-paper .q-terms,.quote-paper .q-notes{font-size:14pt!important}.quote-paper .q-sales{font-size:15pt!important}.quote-paper .q-table{width:100%!important;table-layout:fixed!important}.quote-paper .q-table th,.quote-paper .q-table td{overflow:hidden!important;overflow-wrap:anywhere!important;word-break:break-word!important}`;document.head.appendChild(s)}
function share(){let url=location.origin+location.pathname;window.copyInstallLink=async()=>{try{await navigator.clipboard.writeText(url);alert('安裝連結已複製')}catch(_){prompt('請複製：',url)}};window.shareInstallLink=async()=>{try{if(navigator.share)return navigator.share({title:'鴻繽科技 CRM',url})}catch(_){}window.copyInstallLink()}}
function boot(){version();css();masterUI();cardUI();refreshLists();bindEstimate();wrapQuote();pdfButton();share();fourRows();fitNums();new MutationObserver(()=>requestAnimationFrame(()=>{fourRows();fitNums()})).observe(document.body,{subtree:true,childList:true,characterData:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();