(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const norm=v=>String(v??'').trim().toLowerCase().replace(/[\s　]+/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const MASTER='hongbin_crm_master_r70',CARDIMG='hongbin_crm_card_images_r71',PNOTE='hongbin_crm_project_notes_r71';
function master(){try{return Object.assign({customers:[],products:[],suppliers:[]},JSON.parse(localStorage.getItem(MASTER)||'{}'))}catch(_){return {customers:[],products:[],suppliers:[]}}}
function setVersion(){window.CRM_VERSION='R71';document.title='鴻繽科技 CRM｜R71 Integrated Beta';$$('.content,.status,.sub').forEach(e=>{if(/目前版本：R(?:68|69|70|71)/.test(e.textContent||''))e.innerHTML=e.innerHTML.replace(/目前版本：R(?:68|69|70|71)(?: Integrated Beta)?/g,'目前版本：R71 Integrated Beta').replace(/更新日期：[^<\n]*/g,'更新日期：2026-08-27')})}
function installCss(){if($('#r71-style'))return;const s=document.createElement('style');s.id='r71-style';s.textContent=`
.r71-host{position:relative!important}.r71-box{position:absolute;z-index:100000;left:0;right:0;top:calc(100% + 4px);max-height:240px;overflow:auto;background:#0b0f13;border:1px solid #9b7432;border-radius:8px;box-shadow:0 10px 24px #0009;display:none}.r71-box.show{display:block}.r71-opt{display:block;width:100%;padding:11px 13px;border:0;border-bottom:1px solid #333;background:#11171d;color:#eee3d6;text-align:left;font-size:17px}.r71-empty{padding:11px 13px;color:#a89b8d}.r71-hidden{display:none!important}#r70MasterResults{max-height:420px;overflow-y:auto;-webkit-overflow-scrolling:touch;border:1px solid #3f464d;border-radius:8px;margin-top:10px}#r70MasterResults .r70-row{padding:9px 10px;border-bottom:1px solid #333}.r71-card-preview{width:100%;max-height:180px;object-fit:contain;border-radius:8px;margin:8px 0;background:#080b0e}.r71-file-wrap{border:1px solid #454b51;border-radius:8px;padding:12px;background:#10151a;margin-bottom:10px}.r71-file-wrap input[type=file]{font-size:16px!important}.r71-note{margin-top:8px}`;document.head.appendChild(s)}
function names(){const m=master();return [...new Set(m.customers.map(x=>x.name).filter(Boolean))]}
function productPool(customer){const m=master(),q=norm(customer);if(!q)return m.products;const exact=m.customers.find(x=>norm(x.name)===q);return exact?m.products.filter(x=>norm(x.customerName)===norm(exact.name)):m.products}
function attachCandidate(input,provider,onPick){if(!input||input.dataset.r71Cand)return;input.dataset.r71Cand='1';input.removeAttribute('list');const host=input.parentElement;if(!host)return;host.classList.add('r71-host');const box=document.createElement('div');box.className='r71-box';host.appendChild(box);const hide=()=>box.classList.remove('show');const show=()=>{const q=norm(input.value);if(!q){hide();return}const vals=[...new Set(provider().filter(Boolean))].filter(v=>norm(v).includes(q)).slice(0,25);box.innerHTML=vals.length?vals.map(v=>`<button type="button" class="r71-opt" data-v="${esc(v)}">${esc(v)}</button>`).join(''):'<div class="r71-empty">沒有符合資料</div>';box.classList.add('show')};input.addEventListener('input',show);input.addEventListener('focus',()=>{if(input.value.trim())show()});input.addEventListener('blur',()=>setTimeout(hide,120));box.addEventListener('pointerdown',e=>{const b=e.target.closest('.r71-opt');if(!b)return;e.preventDefault();input.value=b.dataset.v||b.textContent.trim();hide();input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));onPick?.(input.value)})}
function installCandidates(){['vCustomer','qCustomer','qdCustomer','pCustomer','cCustomer','mCustomer','tCustomer','cuSearch'].forEach(id=>attachCandidate(document.getElementById(id),names));const bindProduct=(inp,customerInp)=>attachCandidate(inp,()=>productPool(customerInp?.value).flatMap(x=>[x.name,x.customerPartNo,x.supplierPartNo]),v=>{const arr=productPool(customerInp?.value),k=norm(v),p=arr.find(x=>[x.name,x.customerPartNo,x.supplierPartNo].some(y=>norm(y)===k));if(!p)return;if(inp.id==='qProductName'||inp.id==='qModel')window.R70_COMPLETE?.findProduct&&inp.dispatchEvent(new Event('change',{bubbles:true}));});bindProduct(document.getElementById('qProductName'),document.getElementById('qCustomer'));bindProduct(document.getElementById('qModel'),document.getElementById('qCustomer'));$$('#qdItemsEditor .q-item-card').forEach(card=>{const ins=card.querySelectorAll('input');if(ins[0])bindProduct(ins[0],document.getElementById('qdCustomer'));if(ins[1])bindProduct(ins[1],document.getElementById('qdCustomer'))})}
function searchInput(panel){return panel?.querySelector('input[type="search"],input[placeholder*="搜尋"]')||null}
function itemFilter(panel,{blankHide=false}={}){if(!panel||panel.dataset.r71Filter)return;const input=searchInput(panel);if(!input)return;panel.dataset.r71Filter='1';const apply=()=>requestAnimationFrame(()=>{const q=norm(input.value);const items=$$('.item').filter(x=>panel.contains(x));let shown=0;items.forEach(it=>{const ok=q?norm(it.textContent).includes(q):!blankHide;it.classList.toggle('r71-hidden',!ok);if(ok)shown++});let msg=panel.querySelector('.r71-filter-msg');if(!msg){msg=document.createElement('div');msg.className='status r71-filter-msg';const list=panel.querySelector('#customerGroupList')||items[0]?.parentElement;list?.parentElement?.insertBefore(msg,list||null)}if(msg)msg.textContent=q?(shown?'': '查無符合紀錄'):(blankHide?'請輸入搜尋條件':'')});input.addEventListener('input',apply);panel.querySelectorAll('select').forEach(s=>s.addEventListener('change',apply));new MutationObserver(apply).observe(panel,{subtree:true,childList:true});apply()}
function installFilters(){itemFilter(document.getElementById('customers'),{blankHide:true});itemFilter(document.getElementById('contacts'));itemFilter(document.getElementById('todos'));itemFilter(document.getElementById('projects'),{blankHide:true})}
function fixTodoStatus(){const panel=document.getElementById('todos');if(!panel)return;const apply=()=>panel.querySelectorAll('input[type="checkbox"]').forEach(cb=>{const item=cb.closest('.item');if(!item)return;const walker=document.createTreeWalker(item,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;if(/未完成|已完成/.test(n.nodeValue||'')){n.nodeValue=(n.nodeValue||'').replace(/未完成|已完成/g,cb.checked?'已完成':'未完成');break}}});panel.addEventListener('change',e=>{if(e.target.matches('input[type="checkbox"]'))setTimeout(apply,0)});new MutationObserver(apply).observe(panel,{subtree:true,childList:true});apply()}
function projectFieldByLabel(text){const panel=document.getElementById('projects');if(!panel)return null;for(const l of panel.querySelectorAll('label'))if((l.textContent||'').includes(text))return l.parentElement?.querySelector('input,select,textarea')||l.nextElementSibling;return null}
function installProjectStage(){const panel=document.getElementById('projects');if(!panel)return;const old=projectFieldByLabel('專案階段');if(old&&old.tagName!=='SELECT'&&!old.dataset.r71Stage){const s=document.createElement('select');for(const k of ['進行中','已成交','暫停','結案','取消']){const o=document.createElement('option');o.value=o.textContent=k;s.appendChild(o)}for(const a of [...old.attributes])if(!['type','list'].includes(a.name))s.setAttribute(a.name,a.value);s.value=['進行中','已成交','暫停','結案','取消'].includes(old.value)?old.value:'進行中';old.replaceWith(s)}let note=document.getElementById('r71ProjectNote');if(!note){const stage=projectFieldByLabel('專案階段');if(stage){const wrap=document.createElement('div');wrap.className='full r71-note';wrap.innerHTML='<label>進度註記</label><textarea id="r71ProjectNote" placeholder="例如：客戶測試樣品中、等待採購確認價格"></textarea>';stage.parentElement?.after(wrap);note=wrap.querySelector('textarea')}}const getName=()=>projectFieldByLabel('專案名稱')?.value?.trim()||'';panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(/新增|儲存/.test(b.textContent||'')){const n=getName();if(n&&note){let m={};try{m=JSON.parse(localStorage.getItem(PNOTE)||'{}')}catch(_){}m[n]=note.value.trim();localStorage.setItem(PNOTE,JSON.stringify(m))}}if(/編輯/.test(b.textContent||'')){setTimeout(()=>{const n=getName();if(!n||!note)return;try{note.value=JSON.parse(localStorage.getItem(PNOTE)||'{}')[n]||''}catch(_){note.value=''}},50)}});const decorate=()=>{let m={};try{m=JSON.parse(localStorage.getItem(PNOTE)||'{}')}catch(_){}panel.querySelectorAll('.item').forEach(it=>{if(it.querySelector('.r71-progress-note'))return;const title=it.querySelector('.item-title')?.textContent?.trim()||'';const key=Object.keys(m).find(k=>title.includes(k));if(key&&m[key]){const d=document.createElement('div');d.className='content r71-progress-note';d.textContent='進度註記：'+m[key];it.appendChild(d)}})};new MutationObserver(decorate).observe(panel,{subtree:true,childList:true});decorate()}
function installMasterScroll(){const box=document.getElementById('r70MasterResults');if(box){box.style.maxHeight='420px';box.style.overflowY='auto'}}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1100,r=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*r);c.height=Math.round(img.height*r);c.getContext('2d').drawImage(img,0,0,c.width,c.height);let q=.72,data=c.toDataURL('image/jpeg',q);while(data.length>180000&&q>.35){q-=.08;data=c.toDataURL('image/jpeg',q)}URL.revokeObjectURL(url);resolve(data)};img.onerror=reject;img.src=url})}
function installCardPhoto(){const sec=document.getElementById('businessCardScan'),file=document.getElementById('bcImage');if(!sec||!file)return;const p=file.parentElement;if(p&&!p.classList.contains('r71-file-wrap'))p.classList.add('r71-file-wrap');let preview=document.getElementById('r71CardPreview');if(!preview){preview=document.createElement('img');preview.id='r71CardPreview';preview.className='r71-card-preview';preview.style.display='none';file.after(preview)}file.addEventListener('change',async()=>{const f=file.files?.[0];if(!f)return;try{preview.src=await compressImage(f);preview.style.display='block'}catch(_){}});const save=document.getElementById('r70CardSave');if(save&&!save.dataset.r71Photo){save.dataset.r71Photo='1';save.addEventListener('click',()=>{const company=document.getElementById('bcCompany')?.value.trim(),name=document.getElementById('bcName')?.value.trim();if(!company||!name||!preview?.src?.startsWith('data:image'))return;let m={};try{m=JSON.parse(localStorage.getItem(CARDIMG)||'{}')}catch(_){}m[norm(company)+'|'+norm(name)]=preview.src;localStorage.setItem(CARDIMG,JSON.stringify(m))},true)}}
async function loadPdf(){if(!window.html2canvas)await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)});if(!window.jspdf)await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function pdfR71(){const popup=window.open('about:blank','_blank');try{window.renderQuoteDocument?.();window.paginateQuotePages?.();await loadPdf();const pages=[...document.querySelectorAll('#quotePages .quote-paper')];if(!pages.length)throw new Error('目前沒有報價單');const PDF=window.jspdf.jsPDF,pdf=new PDF({orientation:'portrait',unit:'mm',format:'a4'});for(let i=0;i<pages.length;i++){const c=pages[i].cloneNode(true);c.style.transform='none';c.style.width='794px';c.style.margin='0';c.style.position='fixed';c.style.left='-10000px';document.body.appendChild(c);const cv=await html2canvas(c,{scale:2,backgroundColor:'#fff',useCORS:true});c.remove();if(i)pdf.addPage();pdf.addImage(cv.toDataURL('image/jpeg',.94),'JPEG',0,0,210,297)}const blob=pdf.output('blob'),url=URL.createObjectURL(blob);if(popup)popup.location.href=url;else{const a=document.createElement('a');a.href=url;a.download=`報價單_${document.getElementById('qdNo')?.value||Date.now()}.pdf`;a.click()}setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){popup?.close();alert('PDF 產生失敗：'+(e?.message||e))}}
function saveFormal(){for(const n of ['saveQuoteDocument','saveFormalQuote','saveQuoteDoc'])if(typeof window[n]==='function'){window[n]();return}const data={at:new Date().toISOString(),no:document.getElementById('qdNo')?.value||'',customer:document.getElementById('qdCustomer')?.value||'',contact:document.getElementById('qdContact')?.value||'',tel:document.getElementById('qdTel')?.value||'',fax:document.getElementById('qdFax')?.value||'',items:window.quoteDocItems||[]};let a=[];try{a=JSON.parse(localStorage.getItem('hongbin_crm_formal_quotes_r71')||'[]')}catch(_){}a.unshift(data);localStorage.setItem('hongbin_crm_formal_quotes_r71',JSON.stringify(a));alert('報價已儲存')}
function installQuoteActions(){const sec=document.getElementById('quoteDocument');if(!sec)return;sec.querySelectorAll('button').forEach(b=>{if(/列印|PDF/.test(b.textContent||'')){b.textContent='產生 PDF／列印';b.onclick=pdfR71;b.dataset.r71Pdf='1'}});if(!document.getElementById('r71SaveQuote')){const target=[...sec.querySelectorAll('button')].find(b=>/PDF|列印/.test(b.textContent||''));if(target){const b=document.createElement('button');b.id='r71SaveQuote';b.type='button';b.className='secondary';b.textContent='儲存報價';b.onclick=saveFormal;target.parentElement?.insertBefore(b,target)}}}
function fitMargin(){['#margin','#quoteMargin','#qMargin'].forEach(s=>{const e=$(s);if(!e)return;e.style.fontSize='';let z=parseFloat(getComputedStyle(e).fontSize)||28;while(e.scrollWidth>(e.parentElement?.clientWidth||100)-8&&z>12){z--;e.style.fontSize=z+'px'}})}
function boot(){installCss();setVersion();installCandidates();installFilters();fixTodoStatus();installProjectStage();installMasterScroll();installCardPhoto();installQuoteActions();fitMargin();let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{setVersion();installCandidates();installMasterScroll();installCardPhoto();installQuoteActions();fitMargin()},80)}).observe(document.body,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(()=>{installFilters();installCandidates();installProjectStage();installQuoteActions();setVersion()},80));window.R71={version:'R71 Integrated Beta',pdfR71,saveFormal}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120));else setTimeout(boot,120);
})();