(()=>{'use strict';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)], norm=v=>String(v??'').trim().toLowerCase().replace(/[\s　]+/g,''), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const MASTER='hongbin_crm_master_r70',CRM='hongbin_personal_crm_v3',PROG='hongbin_crm_project_progress_r72';
function master(){try{return Object.assign({customers:[],products:[],suppliers:[]},JSON.parse(localStorage.getItem(MASTER)||'{}'))}catch(_){return {customers:[],products:[],suppliers:[]}}}
function crm(){try{return JSON.parse(localStorage.getItem(CRM)||'{}')}catch(_){return {}}}
function saveCrm(d){localStorage.setItem(CRM,JSON.stringify(d))}
function setVersion(){window.CRM_VERSION='R72';document.title='鴻繽科技 CRM｜R72 Integrated Beta';$$('.content,.status,.sub').forEach(e=>{if(/目前版本：R(?:68|69|70|71|72)/.test(e.textContent||''))e.innerHTML=e.innerHTML.replace(/目前版本：R(?:68|69|70|71|72)(?: Integrated Beta)?/g,'目前版本：R72 Integrated Beta').replace(/更新日期：[^<\n]*/g,'更新日期：2026-08-28')})}
function css(){if($('r72-style'))return;const s=document.createElement('style');s.id='r72-style';s.textContent='.r72-product-info{font-size:15px;color:#c9b99f;margin:6px 0}.r72-top{display:block;width:max-content;max-width:100%;margin:16px auto 4px;padding:8px 15px;border:1px solid #565d63;border-radius:7px;background:linear-gradient(180deg,#242a31,#0e1216);color:#d7cfc6;font-weight:800}.r72-card-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.r72-ocr-tip{font-size:14px;color:#b8ada1;margin-top:7px}';document.head.appendChild(s)}
function customerExact(name){const q=norm(name);return master().customers.find(c=>norm(c.name)===q)||null}
function customerProducts(name){const c=customerExact(name);return c?master().products.filter(p=>norm(p.customerName)===norm(c.name)):[]}
function productLabel(p){return [p.name,p.customerPartNo||p.supplierPartNo].filter(Boolean).join('｜')}
function findProduct(name,q){const k=norm(q);return customerProducts(name).find(p=>[p.name,p.customerPartNo,p.supplierPartNo,productLabel(p)].some(v=>norm(v)===k))||null}
function candidate(input,provider,pick,{showOnFocus=false}={}){if(!input)return;input.removeAttribute('list');const old=input.parentElement?.querySelector(':scope > .r72-box');if(old)old.remove();const host=input.parentElement;if(!host)return;host.style.position='relative';const box=document.createElement('div');box.className='r71-box r72-box';host.appendChild(box);const hide=()=>box.classList.remove('show');const render=()=>{const q=norm(input.value),all=provider();if(!q&&!showOnFocus){hide();return}const vals=all.filter(x=>!q||norm(x.label||x).includes(q)).slice(0,30);box.innerHTML=vals.length?vals.map((x,i)=>`<button type="button" class="r71-opt" data-i="${i}">${esc(x.label||x)}</button>`).join(''):'<div class="r71-empty">沒有符合資料</div>';box.classList.add('show');box.onclick=e=>{const b=e.target.closest('button');if(!b)return;const x=vals[+b.dataset.i];input.value=x.value||x.label||x;hide();pick?.(x);input.dispatchEvent(new Event('change',{bubbles:true}))}};input.oninput=render;input.onfocus=render;input.addEventListener('blur',()=>setTimeout(hide,160));}
function quoteCandidates(){for(const id of ['qCustomer','qdCustomer']){const inp=$(id);candidate(inp,()=>master().customers.map(c=>({label:c.name,value:c.name})),()=>{document.querySelectorAll('.r72-box').forEach(b=>b.classList.remove('show'));updateProductInfo();installProductCandidates()})}installProductCandidates();updateProductInfo()}
function updateProductInfo(){for(const [cid,anchor] of [['qCustomer','qProductName'],['qdCustomer','qdItemsEditor']]){const c=$(cid),a=$(anchor);if(!c||!a)continue;let info=document.querySelector(`[data-r72-info="${cid}"]`);if(!info){info=document.createElement('div');info.className='r72-product-info';info.dataset.r72Info=cid;(a.parentElement||a).before(info)}const n=customerProducts(c.value).length;info.textContent=c.value.trim()?(n?`此客戶已有 ${n} 項產品，可點品名／品號選擇。`:'此客戶目前沒有已匯入產品。'):''}}
function installProductCandidates(){const bind=(inp,cust,apply)=>candidate(inp,()=>customerProducts(cust.value).map(p=>({label:productLabel(p),value:p.name,p})),x=>apply(x.p),{showOnFocus:true});const qC=$('qCustomer');if(qC){const apply=p=>{if(!p)return;$('qProductName').value=p.name||'';$('qModel').value=p.customerPartNo||p.supplierPartNo||'';$('qSpec').value=p.package||p.unit||'';$('qMoq').value=p.moq||p.supplierUnit||p.unit||'';if(p.price!=null)$('qPrice').value=p.price;$('qPrice')?.dispatchEvent(new Event('input',{bubbles:true}))};bind($('qProductName'),qC,apply);bind($('qModel'),qC,apply)}const dc=$('qdCustomer');if(dc)$$('#qdItemsEditor .q-item-card').forEach((card,i)=>{const ins=card.querySelectorAll('input');const apply=p=>{if(!p||!window.quoteDocItems?.[i])return;Object.assign(window.quoteDocItems[i],{name:p.name||'',model:p.customerPartNo||p.supplierPartNo||'',spec:p.package||p.unit||'',price:p.price??'',moq:p.moq||p.supplierUnit||p.unit||''});window.renderQuoteDocEditor?.();window.renderQuoteDocument?.();setTimeout(installProductCandidates,0)};if(ins[0])bind(ins[0],dc,apply);if(ins[1])bind(ins[1],dc,apply)})}
function projectFields(){const p=$('projects');if(!p)return {};const by=t=>[...p.querySelectorAll('label')].find(l=>(l.textContent||'').includes(t))?.parentElement?.querySelector('input,select,textarea');return {name:by('專案名稱'),stage:by('專案階段')}}
function projectProgress(){const p=$('projects');if(!p)return;const {stage}=projectFields();if(stage&&stage.tagName==='SELECT'){const allowed=['進行中','已成交','暫停','結案','取消'];[...stage.options].forEach(o=>{if(!allowed.includes(o.value))o.remove()});for(const v of allowed)if(![...stage.options].some(o=>o.value===v))stage.add(new Option(v,v))}if(!$('r72ProjectProgress')&&stage){const w=document.createElement('div');w.innerHTML='<label>進度</label><select id="r72ProjectProgress"><option value="">未設定</option><option>初步接洽</option><option>需求確認</option><option>送樣中</option><option>客戶測試中</option><option>報價中</option><option>待客戶確認</option><option>待採購確認</option><option>成交準備</option></select>';stage.parentElement.after(w)}if(!$('r71ProjectNote')&&stage){const w=document.createElement('div');w.className='full';w.innerHTML='<label>進度註記</label><textarea id="r71ProjectNote" placeholder="補充目前進度"></textarea>';stage.parentElement.after(w)}p.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const f=projectFields(),n=f.name?.value?.trim();if(!n)return;let m={};try{m=JSON.parse(localStorage.getItem(PROG)||'{}')}catch(_){}if(/新增|儲存/.test(b.textContent||'')){m[n]={progress:$('r72ProjectProgress')?.value||'',note:$('r71ProjectNote')?.value||''};localStorage.setItem(PROG,JSON.stringify(m))}if(/編輯/.test(b.textContent||''))setTimeout(()=>{let x={};try{x=JSON.parse(localStorage.getItem(PROG)||'{}')[n]||{}}catch(_){}if($('r72ProjectProgress'))$('r72ProjectProgress').value=x.progress||'';if($('r71ProjectNote'))$('r71ProjectNote').value=x.note||''},50)},true)}
function backTop(){for(const p of $$('.panel')){if(p.querySelector('.r72-top'))continue;const b=document.createElement('button');b.type='button';b.className='r72-top';b.textContent='↑ 返回頂部';b.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});p.appendChild(b)}}
function cleanPhone(s){return String(s||'').replace(/[^0-9+()#extEXT分機-]/g,'').replace(/-{2,}/g,'-').trim()}
function betterCardParser(){const old=window.scanBusinessCardLocal;if(typeof old!=='function'||old.__r72)return;const f=async function(){await old.apply(this,arguments);setTimeout(()=>{const tel=$('bcTel'),fax=$('bcFax'),mob=$('bcMobile'),company=$('bcCompany'),name=$('bcName');const raw=[tel?.value,fax?.value].join(' ');const faxM=raw.match(/FAX\s*[:：]?\s*([+\d()\s-]{7,})/i),telM=raw.match(/TEL\s*[:：]?\s*([+\d()\s-]{7,})/i);if(telM&&tel)tel.value=cleanPhone(telM[1]);if(faxM&&fax)fax.value=cleanPhone(faxM[1]);if(mob)mob.value=cleanPhone(mob.value);if(name&&!/[\u3400-\u9fff]{2,4}/.test(name.value))name.value='';if(company&&company.value&&!/(公司|企業|科技|實業|股份|有限公司)/.test(company.value))company.value='';const s=$('bcStatus');if(s)s.textContent='辨識完成。請確認欄位；辨識不確定的欄位會留白，避免誤存。'},80)};f.__r72=1;window.scanBusinessCardLocal=f}
function cardActions(){const sec=$('businessCardScan');if(!sec)return;let box=$('r72CardActions');if(!box){box=document.createElement('div');box.id='r72CardActions';box.className='r72-card-actions';box.innerHTML='<button type="button" class="secondary" id="r72LinkCustomer">連結既有客戶</button><button type="button" class="primary" id="r72NewCustomer">建立新客戶</button>';sec.querySelector('.card')?.appendChild(box);const tip=document.createElement('div');tip.className='r72-ocr-tip';tip.textContent='建立新客戶會使用你確認過的名片欄位；若公司已存在則改為連結，避免重複。';box.after(tip)}$('r72LinkCustomer').onclick=()=>{const n=$('bcCompany')?.value.trim();if(!n)return alert('請先確認公司名稱');const c=customerExact(n);if(!c)return alert('找不到既有客戶，請改用「建立新客戶」');$('r70CardSave')?.click()};$('r72NewCustomer').onclick=()=>{const n=$('bcCompany')?.value.trim();if(!n)return alert('請先確認公司名稱');if(customerExact(n)){alert('此公司已存在，將改為連結既有客戶');$('r70CardSave')?.click();return}const m=master();m.customers.push({name:n,contact:$('bcName')?.value.trim()||'',tel:$('bcTel')?.value.trim()||'',fax:$('bcFax')?.value.trim()||'',mobile:$('bcMobile')?.value.trim()||'',email:$('bcEmail')?.value.trim()||'',address:$('bcAddress')?.value.trim()||'',source:'business-card'});m.updatedAt=new Date().toISOString();localStorage.setItem(MASTER,JSON.stringify(m));const d=crm();d.customers=Array.isArray(d.customers)?d.customers:[];d.customers.push({id:Date.now(),name:n});saveCrm(d);alert('新客戶已建立並連結名片');location.reload()}}
function boot(){css();setVersion();quoteCandidates();projectProgress();backTop();betterCardParser();cardActions();let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{setVersion();installProductCandidates();updateProductInfo();backTop();cardActions()},100)}).observe(document.body,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(()=>{quoteCandidates();projectProgress();backTop();cardActions()},120))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,150));else setTimeout(boot,150);
})();